=== mYstar/JSPEval/xml/model.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.htw-dresden.de/JSPeval"
  xmlns="http://www.htw-dresden.de/JSPeval"
  elementFormDefault="qualified">

  <!-- definition of simple datatypes -->

  <!-- a deadline is defined as the number of timeunits since the start of the
  production when the production of a job shall be ready -->
  <xs:simpleType name="t_deadline">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0.0"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- production_units are a number of resources that are used in the
  production of a job. These are used as measurement units for WIP calculation.
  -->
  <xs:simpleType name="t_production_units">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- a starttime is defined as the number of timeunits since the start of the
  production when the job can start processing-->
  <xs:simpleType name="t_starttime">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0.0"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- the duration is defined as the number of timeunits an operation needs
  from start to finish -->
  <xs:simpleType name="t_duration">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0.0"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- a setuptime is composed of 2 operations and a duration a machine needs to
  switch from prosessing the one operation to the other -->
  <xs:complexType name="t_setuptime">
    <xs:sequence>
      <xs:element name="from_operation" type="xs:string"/>
      <xs:element name="to_operation" type="xs:string"/>
      <xs:element name="setup_duration" type="t_duration"/>
    </xs:sequence>

  </xs:complexType>

  <!-- definition of complex types -->

  <xs:element name="machine">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        A machine is identified by an ID. It can process a different set of
        operations, but this is defined at the operation.
      </xs:documentation>
    </xs:annotation>

    <xs:complexType>
      <xs:attribute name="machine_id" type="xs:string"/>
    </xs:complexType>

    <xs:key name="machineid">
      <xs:selector xpath="machine"/>    
      <xs:field xpath="@machine_id"/>
    </xs:key>
  </xs:element>

  <xs:element name="operation">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        An operation has a defined duration and can be processed by a list of
        machines. The ID of the operation has to be unique.
      </xs:documentation>
    </xs:annotation>

    <xs:complexType>
      <xs:sequence>
        <xs:element name="op_duration" type="t_duration"/>
        <xs:element name="allowed_machine" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="operation_id" type="xs:string"/>
    </xs:complexType>

    <xs:key name="operationid">
      <xs:selector xpath="operation"/>    
      <xs:field xpath="@operation_id"/>
    </xs:key>
    <xs:keyref name="allowedmachines" refer="machineid">
      <xs:selector xpath="operation"/>
      <xs:field xpath="allowed_machine"/>
    </xs:keyref>
  </xs:element>

  <xs:element name="job">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        Jobs consist of operations and have a deadline.
      </xs:documentation>
    </xs:annotation>

    <xs:complexType>
      <xs:sequence>
        <xs:element name="starttime" type="t_starttime"/>
        <xs:element name="deadline" type="t_deadline"/>
        <xs:element name="production_units" type="t_production_units"/>
        <xs:element ref="operation" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="job_id" type="xs:string"/>
    </xs:complexType>

    <xs:key name="jobid">
      <xs:selector xpath="job"/>    
      <xs:field xpath="@job_id"/>
    </xs:key>
    <xs:keyref name="joboperation" refer="operationid">
      <xs:selector xpath="job"/>
      <xs:field xpath="operation"/>
    </xs:keyref>
  </xs:element>

  <xs:element name="setuptimes">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        There must be a setuptime for every operation to every other. undefined setuptimes will be asumed as 0.
      </xs:documentation>
    </xs:annotation>

    <xs:complexType>
      <xs:sequence> 
        <xs:element name="setuptime" type="t_setuptime" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>

    <xs:unique name="fromtopair">
      <xs:selector xpath="setuptime"/>
      <xs:field xpath="from_operation"/>
      <xs:field xpath="to_operation"/>
    </xs:unique>
    <xs:keyref name="fromoperation" refer="operationid">
      <xs:selector xpath="setuptime"/>
      <xs:field xpath="from_operation"/>
    </xs:keyref>
    <xs:keyref name="tooperatioan" refer="operationid">
      <xs:selector xpath="setuptime"/>
      <xs:field xpath="to_operation"/>
    </xs:keyref>
  </xs:element>

  <xs:element name="jsp-model">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        A model contains all information required for instanciation (jobs, machines, setuptimes).
      </xs:documentation>
    </xs:annotation>

    <xs:complexType>
      <xs:sequence>
        <xs:element ref="machine" maxOccurs="unbounded"/>
        <xs:element ref="job" maxOccurs="unbounded"/>
        <xs:element ref="setuptimes"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== mYstar/JSPEval/xml/example.xml
<?xml version="1.0" encoding="UTF-8" ?>

<jsp-model 
  xmlns="http://www.htw-dresden.de/JSPeval"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.htw-dresden.de/JSPeval file:///home/est/cloud/promotion/code/JSPEval/xml/model.xsd">

  <!-- definition of the machine ids-->
  <machine machine_id="001"/>
  <machine machine_id="002"/>
  <machine machine_id="003"/>

  <!-- listing of all jobs and their operations. All times are relative to the
  model start. releasetime is the earliest time the job can begin processing.
  deadline is the planned time when the job shall be ready operations have a
  duration and a list of allowed machines for processing -->
  <job job_id="j01">
    <releasetime>0.0</releasetime>
    <deadline>25.0</deadline>
    <weight>1.0</weight>
    <lotsize>1</lotsize>
    <operation operation_id="o1">
      <op_duration>5.0</op_duration>
      <allowed_machine>001</allowed_machine>
      <allowed_machine>002</allowed_machine>
    </operation>
    <operation operation_id="o2">
      <op_duration>15.0</op_duration>
      <allowed_machine>003</allowed_machine>
      <allowed_machine>002</allowed_machine>
    </operation>
  </job>
  
  <job job_id="j02">
    <releasetime>10.0</releasetime>
    <deadline>50.0</deadline>
    <weight>1.5</weight>
    <lotsize>1</lotsize>
    <operation operation_id="o21">
      <op_duration>15.0</op_duration>
      <allowed_machine>002</allowed_machine>
    </operation>
    <operation operation_id="o22">
      <op_duration>15.0</op_duration>
      <allowed_machine>003</allowed_machine>
      <allowed_machine>001</allowed_machine>
    </operation>
  </job>

  <!-- list of the setuptimes, non existing pairs will be assumed as 0.0
  setuptime-->
  <setuptimes>
    <setuptime>
      <from_operation>o1</from_operation>
      <to_operation>o2</to_operation>
      <setup_duration>2.0</setup_duration>      
    </setuptime>
    <setuptime>
      <from_operation>o2</from_operation>
      <to_operation>o1</to_operation>
      <setup_duration>1.5</setup_duration>      
    </setuptime>
    <setuptime>
      <from_operation>o2</from_operation>
      <to_operation>o21</to_operation>
      <setup_duration>5.5</setup_duration>      
    </setuptime>
    <setuptime>
      <from_operation>o22</from_operation>
      <to_operation>o2</to_operation>
      <setup_duration>2.5</setup_duration>      
    </setuptime>
  </setuptimes>
</jsp-model>

=== mYstar/JSPEval/test/complexmodel.xml
<?xml version="1.0" encoding="UTF-8" ?>

<jsp-model 
  xmlns="http://www.htw-dresden.de/JSPeval"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.htw-dresden.de/JSPeval file:///home/est/cloud/promotion/code/JSPEval/xml/model.xsd">

  <!-- definition of the machine ids-->
  <machine machine_id="m0"/>
  <machine machine_id="m1"/>
  <machine machine_id="m2"/>
  <machine machine_id="m3"/>

  <!-- listing of all jobs and their operations. All times are relative to the
  model start. starttime is the earliest time the job can begin processing.
  deadline is the planned time when the job shall be ready operations have a
  duration and a list of allowed machines for processing -->
  <job job_id="j0">
    <starttime>0.0</starttime>
    <deadline>30.0</deadline>
    <lotsize>2</lotsize>
    <operation operation_id="o00">
      <op_duration>7.0</op_duration>
      <allowed_machine>m0</allowed_machine>
      <allowed_machine>m2</allowed_machine>
    </operation>
    <operation operation_id="o01">
      <op_duration>12.0</op_duration>
      <allowed_machine>m1</allowed_machine>
      <allowed_machine>m3</allowed_machine>
    </operation>
  </job>
  
  <job job_id="j1">
    <starttime>15.0</starttime>
    <deadline>150.0</deadline>
    <lotsize>1</lotsize>
    <operation operation_id="o10">
      <op_duration>15.0</op_duration>
      <allowed_machine>m0</allowed_machine>
      <allowed_machine>m1</allowed_machine>
      <allowed_machine>m3</allowed_machine>
    </operation>
    <operation operation_id="o11">
      <op_duration>25.0</op_duration>
      <allowed_machine>m0</allowed_machine>
      <allowed_machine>m2</allowed_machine>
    </operation>
    <operation operation_id="o12">
      <op_duration>10.0</op_duration>
      <allowed_machine>m0</allowed_machine>
      <allowed_machine>m2</allowed_machine>
      <allowed_machine>m3</allowed_machine>
    </operation>
    <operation operation_id="o13">
      <op_duration>5.0</op_duration>
      <allowed_machine>m0</allowed_machine>
      <allowed_machine>m2</allowed_machine>
      <allowed_machine>m3</allowed_machine>
    </operation>
    <operation operation_id="o14">
      <op_duration>50.0</op_duration>
      <allowed_machine>m1</allowed_machine>
      <allowed_machine>m2</allowed_machine>
      <allowed_machine>m3</allowed_machine>
    </operation>
  </job>

  <job job_id="j2">
    <starttime>30.0</starttime>
    <deadline>100.0</deadline>
    <lotsize>5</lotsize>
    <operation operation_id="o20">
      <op_duration>15.0</op_duration>
      <allowed_machine>m0</allowed_machine>
      <allowed_machine>m1</allowed_machine>
      <allowed_machine>m2</allowed_machine>
      <allowed_machine>m3</allowed_machine>
    </operation>
    <operation operation_id="o21">
      <op_duration>2.0</op_duration>
      <allowed_machine>m2</allowed_machine>
    </operation>
    <operation operation_id="o22">
      <op_duration>13.0</op_duration>
      <allowed_machine>m1</allowed_machine>
      <allowed_machine>m2</allowed_machine>
      <allowed_machine>m3</allowed_machine>
    </operation>
  </job>

  <job job_id="j3">
    <starttime>50.0</starttime>
    <deadline>65.0</deadline>
    <lotsize>4</lotsize>
    <operation operation_id="o30">
      <op_duration>5.0</op_duration>
      <allowed_machine>m0</allowed_machine>
      <allowed_machine>m1</allowed_machine>
      <allowed_machine>m2</allowed_machine>
      <allowed_machine>m3</allowed_machine>
    </operation>
  </job>

  <job job_id="j4">
    <starttime>5.0</starttime>
    <deadline>80.0</deadline>
    <lotsize>2</lotsize>
    <operation operation_id="o40">
      <op_duration>30.0</op_duration>
      <allowed_machine>m3</allowed_machine>
    </operation>
  </job>

  <!-- list of the setuptimes, non existing pairs will be assumed as 0.0
  setuptime-->
  <setuptimes>
    <setuptime>
      <from_operation>o00</from_operation>
      <to_operation>o21</to_operation>
      <setup_duration>2.0</setup_duration>      
    </setuptime>
    <setuptime>
      <from_operation>o11</from_operation>
      <to_operation>o12</to_operation>
      <setup_duration>1.5</setup_duration>      
    </setuptime>
    <setuptime>
      <from_operation>o40</from_operation>
      <to_operation>o01</to_operation>
      <setup_duration>5.5</setup_duration>      
    </setuptime>
    <setuptime>
      <from_operation>o13</from_operation>
      <to_operation>o11</to_operation>
      <setup_duration>2.5</setup_duration>      
    </setuptime>
  </setuptimes>
</jsp-model>

=== mYstar/JSPEval/test/10operations.xml
<?xml version="1.0" encoding="UTF-8" ?>

<jsp-model 
  xmlns="http://www.htw-dresden.de/JSPeval"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.htw-dresden.de/JSPeval file:///home/est/cloud/promotion/code/JSPEval/xml/model.xsd">

  <!-- definition of the machine ids-->
  <machine machine_id="001"/>
  <machine machine_id="002"/>
  <machine machine_id="003"/>
  <machine machine_id="004"/>

  <!-- listing of all jobs and their operations. All times are relative to the
  model start. starttime is the earliest time the job can begin processing.
  deadline is the planned time when the job shall be ready operations have a
  duration and a list of allowed machines for processing -->
  <job job_id="j01">
    <starttime>0.0</starttime>
    <deadline>25.0</deadline>
    <production_units>1</production_units>
    <operation operation_id="o1">
      <op_duration>5.0</op_duration>
      <allowed_machine>001</allowed_machine>
      <allowed_machine>002</allowed_machine>
      <allowed_machine>003</allowed_machine>
      <allowed_machine>004</allowed_machine>
    </operation>
    <operation operation_id="o2">
      <op_duration>15.0</op_duration>
      <allowed_machine>001</allowed_machine>
      <allowed_machine>002</allowed_machine>
      <allowed_machine>003</allowed_machine>
      <allowed_machine>004</allowed_machine>
    </operation>
    <operation operation_id="o3">
      <op_duration>5.0</op_duration>
      <allowed_machine>001</allowed_machine>
      <allowed_machine>002</allowed_machine>
      <allowed_machine>003</allowed_machine>
      <allowed_machine>004</allowed_machine>
    </operation>
  </job>
  
  <job job_id="j02">
    <starttime>10.0</starttime>
    <deadline>80.0</deadline>
    <production_units>2</production_units>
    <operation operation_id="o21">
      <op_duration>15.0</op_duration>
      <allowed_machine>001</allowed_machine>
      <allowed_machine>002</allowed_machine>
      <allowed_machine>003</allowed_machine>
      <allowed_machine>004</allowed_machine>
    </operation>
    <operation operation_id="o22">
      <op_duration>25.0</op_duration>
      <allowed_machine>001</allowed_machine>
      <allowed_machine>002</allowed_machine>
      <allowed_machine>003</allowed_machine>
      <allowed_machine>004</allowed_machine>
    </operation>
    <operation operation_id="o22">
      <op_duration>10.0</op_duration>
      <allowed_machine>001</allowed_machine>
      <allowed_machine>002</allowed_machine>
      <allowed_machine>003</allowed_machine>
      <allowed_machine>004</allowed_machine>
    </operation>
    <operation operation_id="o24">
      <op_duration>5.0</op_duration>
      <allowed_machine>001</allowed_machine>
      <allowed_machine>002</allowed_machine>
      <allowed_machine>003</allowed_machine>
      <allowed_machine>004</allowed_machine>
    </operation>
  </job>

  <job job_id="j03">
    <starttime>20.0</starttime>
    <deadline>50.0</deadline>
    <production_units>3</production_units>
    <operation operation_id="o31">
      <op_duration>15.0</op_duration>
      <allowed_machine>001</allowed_machine>
      <allowed_machine>002</allowed_machine>
      <allowed_machine>003</allowed_machine>
      <allowed_machine>004</allowed_machine>
    </operation>
    <operation operation_id="o32">
      <op_duration>5.0</op_duration>
      <allowed_machine>001</allowed_machine>
      <allowed_machine>002</allowed_machine>
      <allowed_machine>003</allowed_machine>
      <allowed_machine>004</allowed_machine>
    </operation>
    <operation operation_id="o33">
      <op_duration>10.0</op_duration>
      <allowed_machine>001</allowed_machine>
      <allowed_machine>002</allowed_machine>
      <allowed_machine>003</allowed_machine>
      <allowed_machine>004</allowed_machine>
    </operation>
  </job>

  <!-- list of the setuptimes, non existing pairs will be assumed as 0.0
  setuptime-->
  <setuptimes/>
</jsp-model>
